name: e_commerc_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

  #PACKAGES
dependencies:
  flutter:
    sdk: flutter

  #Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  #utitlity packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0

  #Product Specific
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #LOCAL ASSETS
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/images/
    - assets/images/user/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/sign_up_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/

  #LOCAL FONTS
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
